config/routes.rb
Rails.application.routes.draw do
  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/terms_conditions', to: 'static_pages#terms_conditions'
  root  'posts#index'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :posts, only: [:index, :show, :new, :create, :destroy]
  resources :users, only: [:index, :show]
  resources :comments, only: :create
  resources :likings, only: [:create, :destroy]
  resources :friendships, only: [:create, :update, :index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_comments.html.erb
<% post.comments.each do |comment| %>
  <div class="col-12 pt-4">
    <h4><%=link_to comment.user.name, comment.user%> said:</h4>
  </div>
  <div class="col-12">
    <p><%=comment.content%></p>
  </div>
  <div class="col-12 pb-2">
    <span>Comented <%=time_ago_in_words(comment.created_at)%> ago</span>
  </div>
  <hr class="w-100">
<% end %>

app/views/application/_create_new_post.html.erb
<div class="row">
  <button class="btn btn-primary ml-0 my-4" data-toggle="modal" data-target="#myModal">New Post</button>
</div>
 <!-- The Modal -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
    
      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Create New Post </h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      
      <!-- Modal body -->
      <div class="modal-body">
        <%= render partial: 'new_post' %>
      </div>
      
      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
      
    </div>
  </div>
</div>

app/views/application/_head.html.erb
  <head>
    <title>FacebookClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0 shrink-to-fit=no" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
  </head>

app/views/application/_likes.html.erb
<li class="nav-item border-right border-dark px-2">
 <%= like_dislike(post) %>
    (<%=post.likings.size%>)
</li>

app/views/application/_navbar.html.erb
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <%= link_to 'Facebook', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% if user_signed_in? %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to current_user.name, current_user, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Friend Requests (#{current_user.friend_requests.count})", friendships_path, class: "nav-link" %>
        </li>
      <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Users', users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Create Post', new_post_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    </div>
  <% end %>
</nav>

app/views/application/_new_comment.html.erb
<li class="nav-item border-right border-dark px-2">    
  <a class="link" data-toggle="collapse" href="#collapse<%=post.id  %>">Comment</a>
</li>
<li class="nav-item px-2 ">    
  <%= link_to "View Comments", post%> (<%= post.comments.count %>)
</li>

app/views/application/_new_post.html.erb
<%= form_for(:post, url:posts_path) do |f| %>
<div class="form-group">
<%= f.text_area :content, class: 'form-control' %>
</div>
<%= f.submit 'Create Post', class: 'btn btn-primary'  %>
<% end %>

app/views/application/_post.html.erb
<div class="row">
    <h3><%= gravatar_for post.user %> <%= link_to post.user.name, post.user %></h3>
    <%= render partial: 'post_content', locals:{post: post} %>
</div>

app/views/application/_post_content.html.erb
<div class="col-12">
  <span>Posted <%= link_to time_ago_in_words(post.created_at), post %> ago</span>
  <p class="mb-0"><%= post.content %></p>
</div>
<ul class="nav justify-content-between mx-auto">
<%= render partial: 'likes', locals: {post: post}%>
<%= render partial: 'new_comment', locals: {post: post} %>
<%if current_user.id == post.user_id %><li class="nav-item border-left border-dark px-2"><%= link_to 'Delete Post', post_path(post), method: :delete %></li><%end%>
</ul>
   
<div id="collapse<%=post.id  %>" class="collapse w-100" data-parent="#accordion">
  <div class="card-body ">
    <%= form_for :comment, url: comments_path do |f| %>
      <div class="form-group">
        <%= f.text_area :content, class: 'form-control' %>
      </div>

      <%= f.hidden_field :post_id, value: post.id %>
      
      <%= f.submit 'Comment', class: 'btn btn-primary'  %>
    <% end %>
  </div>
</div>
 

app/views/application/_user.html.erb
  <div class="card col-3 mb-4 mx-2" >
    <%= gravatar_for user, class: "card-img-top" %>
    <div class="card-body ">
      <h4 class="card-title"><%= user.name %></h4>
      <p class="card-text"><%= user.email %></p>
      <%= friend_status(user) %>
      <%= link_to 'See Profile', user, class: "btn btn-primary" %>
    </div>
  </div>